/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ACascader: typeof import('../components/ant-form-cpns/index')['ACascader']
  const ACheckbox: typeof import('../components/ant-form-cpns/index')['ACheckbox']
  const ADate: typeof import('../components/ant-form-cpns/index')['ADate']
  const ADateRange: typeof import('../components/ant-form-cpns/index')['ADateRange']
  const AEmpty: typeof import('../components/ant-data-show-cpns/index')['AEmpty']
  const AInput: typeof import('../components/ant-form-cpns/index')['AInput']
  const AInputNumber: typeof import('../components/ant-form-cpns/index')['AInputNumber']
  const ARadio: typeof import('../components/ant-form-cpns/index')['ARadio']
  const ARate: typeof import('../components/ant-form-cpns/index')['ARate']
  const ASelect: typeof import('../components/ant-form-cpns/index')['ASelect']
  const ASlider: typeof import('../components/ant-form-cpns/index')['ASlider']
  const ASpin: typeof import('../components/ant-feedback-cpns/index')['ASpin']
  const ATabs: typeof import('../components/ant-data-show-cpns/index')['ATabs']
  const ATextarea: typeof import('../components/ant-form-cpns/index')['ATextarea']
  const ATime: typeof import('../components/ant-form-cpns/index')['ATime']
  const ATimeLine: typeof import('../components/ant-data-show-cpns/index')['ATimeLine']
  const ATimeRange: typeof import('../components/ant-form-cpns/index')['ATimeRange']
  const ATree: typeof import('../components/ant-data-show-cpns/index')['ATree']
  const ATreeSelect: typeof import('../components/ant-form-cpns/index')['ATreeSelect']
  const AllFileList: typeof import('../components/preview-files/index')['AllFileList']
  const BtnLink: typeof import('../components/ant-comm-cpns/index')['BtnLink']
  const BtnPrimary: typeof import('../components/ant-comm-cpns/index')['BtnPrimary']
  const BtnSolid: typeof import('../components/ant-comm-cpns/index')['BtnSolid']
  const Link: typeof import('react-router-dom')['Link']
  const LoadImage: typeof import('../components/preview-files/load-image/load-image')['LoadImage']
  const LoadPdf: typeof import('../components/preview-files/load-pdf/load-pdf')['LoadPdf']
  const LoadVideo: typeof import('../components/preview-files/index')['LoadVideo']
  const ModalDetail: typeof import('../components/page-cpns/modal-detail/modal-detail')['ModalDetail']
  const ModalForm: typeof import('../components/page-cpns/modal-form/modal-form')['ModalForm']
  const NavLink: typeof import('react-router-dom')['NavLink']
  const Navigate: typeof import('react-router-dom')['Navigate']
  const Outlet: typeof import('react-router-dom')['Outlet']
  const PageDetail: typeof import('../components/page-cpns/page-detail/page-detail')['PageDetail']
  const PageForm: typeof import('../components/page-cpns/page-form/page-form')['PageForm']
  const PageHandle: typeof import('../components/page-cpns/page-handle/page-handle')['PageHandle']
  const PagePagination: typeof import('../components/page-cpns/page-pagination/page-pagination')['PagePagination']
  const PageSearch: typeof import('../components/page-cpns/page-search/page-search')['PageSearch']
  const PageTable: typeof import('../components/page-cpns/page-table/page-table')['PageTable']
  const PreviewFileModal: typeof import('../components/preview-files/preview-file-modal/preview-file-modal')['PreviewFileModal']
  const Route: typeof import('react-router-dom')['Route']
  const Routes: typeof import('react-router-dom')['Routes']
  const StyledModuleTitle: typeof import('../components/page-cpns/page-form/style')['StyledModuleTitle']
  const StyledPageDetail: typeof import('../components/page-cpns/page-detail/style')['StyledPageDetail']
  const StyledPageDetailTitle: typeof import('../components/page-cpns/page-detail/style')['StyledPageDetailTitle']
  const StyledPageForm: typeof import('../components/page-cpns/page-form/style')['StyledPageForm']
  const SuperPage: typeof import('../components/page-cpns/super-page/super-page')['SuperPage']
  const SvgAudit: typeof import('../components/svg/svg-audit')['SvgAudit']
  const SvgAuditRiskFinally: typeof import('../components/svg/svg-audit-risk-finally')['SvgAuditRiskFinally']
  const SvgAuditRiskFirst: typeof import('../components/svg/svg-audit-risk-first')['SvgAuditRiskFirst']
  const SvgAuditRiskSecond: typeof import('../components/svg/svg-audit-risk-second')['SvgAuditRiskSecond']
  const SvgAuditTeamFirst: typeof import('../components/svg/svg-audit-team-first')['SvgAuditTeamFirst']
  const SvgAuditTeamSecond: typeof import('../components/svg/svg-audit-team-second')['SvgAuditTeamSecond']
  const SvgIcon: typeof import('../components/svg/index')['SvgIcon']
  const SvgOrder: typeof import('../components/svg/svg-order')['SvgOrder']
  const SvgSys: typeof import('../components/svg/svg-sys')['SvgSys']
  const SvgSysMenu: typeof import('../components/svg/svg-sys-menu')['SvgSysMenu']
  const SvgSysOrg: typeof import('../components/svg/svg-sys-org')['SvgSysOrg']
  const SvgSysRole: typeof import('../components/svg/svg-sys-role')['SvgSysRole']
  const SvgSysUser: typeof import('../components/svg/svg-sys-user')['SvgSysUser']
  const aCascader: typeof import('../components/ant-form-cpns/a-cascader/a-cascader')['default']
  const aCheckbox: typeof import('../components/ant-form-cpns/a-checkbox/a-checkbox')['default']
  const aDate: typeof import('../components/ant-form-cpns/a-date/a-date')['default']
  const aDateRange: typeof import('../components/ant-form-cpns/a-date-range/a-date-range')['default']
  const aInput: typeof import('../components/ant-form-cpns/a-input/a-input')['default']
  const aInputNumber: typeof import('../components/ant-form-cpns/a-input-number/a-input-number')['default']
  const aModal: typeof import('../components/ant-comm-cpns/a-modal/a-modal')['default']
  const aRadio: typeof import('../components/ant-form-cpns/a-radio/a-radio')['default']
  const aRate: typeof import('../components/ant-form-cpns/a-rate/a-rate')['default']
  const aSelect: typeof import('../components/ant-form-cpns/a-select/a-select')['default']
  const aSlider: typeof import('../components/ant-form-cpns/a-slider/a-slider')['default']
  const aSpin: typeof import('../components/ant-feedback-cpns/a-spin/a-spin')['default']
  const aTabs: typeof import('../components/ant-data-show-cpns/a-tabs/a-tabs')['default']
  const aTextarea: typeof import('../components/ant-form-cpns/a-textarea/a-textarea')['default']
  const aTime: typeof import('../components/ant-form-cpns/a-time/a-time')['default']
  const aTimeLine: typeof import('../components/ant-data-show-cpns/a-time-line/a-time-line')['default']
  const aTimeRange: typeof import('../components/ant-form-cpns/a-time-range/a-time-range')['default']
  const aTree: typeof import('../components/ant-data-show-cpns/a-tree/a-tree')['default']
  const aTreeSelect: typeof import('../components/ant-form-cpns/a-tree-select/a-tree-select')['default']
  const allFileList: typeof import('../components/preview-files/all-file-list/all-file-list')['default']
  const bScroll: typeof import('../components/b-scroll/b-scroll')['default']
  const btnLink: typeof import('../components/ant-comm-cpns/a-button/btn-link/btn-link')['default']
  const btnPrimary: typeof import('../components/ant-comm-cpns/a-button/btn-primary/btn-primary')['default']
  const btnSolid: typeof import('../components/ant-comm-cpns/a-button/btn-solid/btn-solid')['default']
  const commStyle: typeof import('../components/ant-comm-cpns/a-button/comm-style')['default']
  const commSwiper: typeof import('../components/comm-swiper/comm-swiper')['default']
  const commTitle: typeof import('../components/comm-title/comm-title')['default']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const generateDetailItem: typeof import('../components/page-cpns/generate-item/index')['generateDetailItem']
  const generateFormItem: typeof import('../components/page-cpns/generate-item/index')['generateFormItem']
  const generateTableItem: typeof import('../components/page-cpns/generate-item/index')['generateTableItem']
  const lazy: typeof import('react')['lazy']
  const loadImage: typeof import('../components/preview-files/load-image/load-image')['default']
  const loadPdf: typeof import('../components/preview-files/load-pdf/load-pdf')['default']
  const loadVideo: typeof import('../components/preview-files/load-video/load-video')['default']
  const memo: typeof import('react')['memo']
  const modalDetail: typeof import('../components/page-cpns/modal-detail/modal-detail')['default']
  const modalForm: typeof import('../components/page-cpns/modal-form/modal-form')['default']
  const pageDetail: typeof import('../components/page-cpns/page-detail/page-detail')['default']
  const pageForm: typeof import('../components/page-cpns/page-form/page-form')['default']
  const pageHandle: typeof import('../components/page-cpns/page-handle/page-handle')['default']
  const pagePagination: typeof import('../components/page-cpns/page-pagination/page-pagination')['default']
  const pageSearch: typeof import('../components/page-cpns/page-search/page-search')['default']
  const pageTable: typeof import('../components/page-cpns/page-table/page-table')['default']
  const previewFileModal: typeof import('../components/preview-files/preview-file-modal/preview-file-modal')['default']
  const previewImg: typeof import('../components/preview-files/preview-img/preview-img')['default']
  const startTransition: typeof import('react')['startTransition']
  const style: typeof import('../components/preview-files/preview-file-modal/style')['default']
  const superPage: typeof import('../components/page-cpns/super-page/super-page')['default']
  const svgAudit: typeof import('../components/svg/svg-audit')['default']
  const svgAuditRiskFinally: typeof import('../components/svg/svg-audit-risk-finally')['default']
  const svgAuditRiskFirst: typeof import('../components/svg/svg-audit-risk-first')['default']
  const svgAuditRiskSecond: typeof import('../components/svg/svg-audit-risk-second')['default']
  const svgAuditTeamFirst: typeof import('../components/svg/svg-audit-team-first')['default']
  const svgAuditTeamSecond: typeof import('../components/svg/svg-audit-team-second')['default']
  const svgOrder: typeof import('../components/svg/svg-order')['default']
  const svgSys: typeof import('../components/svg/svg-sys')['default']
  const svgSysMenu: typeof import('../components/svg/svg-sys-menu')['default']
  const svgSysOrg: typeof import('../components/svg/svg-sys-org')['default']
  const svgSysRole: typeof import('../components/svg/svg-sys-role')['default']
  const svgSysUser: typeof import('../components/svg/svg-sys-user')['default']
  const useAntdTable: typeof import('ahooks')['useAntdTable']
  const useAsyncEffect: typeof import('ahooks')['useAsyncEffect']
  const useBScroll: typeof import('../hooks/use-b-scroll')['useBScroll']
  const useBoolean: typeof import('ahooks')['useBoolean']
  const useCallback: typeof import('react')['useCallback']
  const useClickAway: typeof import('ahooks')['useClickAway']
  const useContext: typeof import('react')['useContext']
  const useControllableValue: typeof import('ahooks')['useControllableValue']
  const useCookieState: typeof import('ahooks')['useCookieState']
  const useCountDown: typeof import('ahooks')['useCountDown']
  const useCounter: typeof import('ahooks')['useCounter']
  const useCreation: typeof import('ahooks')['useCreation']
  const useDebounce: typeof import('ahooks')['useDebounce']
  const useDebounceEffect: typeof import('ahooks')['useDebounceEffect']
  const useDebounceFn: typeof import('ahooks')['useDebounceFn']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeepCompareEffect: typeof import('ahooks')['useDeepCompareEffect']
  const useDeepCompareLayoutEffect: typeof import('ahooks')['useDeepCompareLayoutEffect']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useDocumentVisibility: typeof import('ahooks')['useDocumentVisibility']
  const useDrag: typeof import('ahooks')['useDrag']
  const useDrop: typeof import('ahooks')['useDrop']
  const useDynamicList: typeof import('ahooks')['useDynamicList']
  const useEffect: typeof import('react')['useEffect']
  const useEventEmitter: typeof import('ahooks')['useEventEmitter']
  const useEventListener: typeof import('ahooks')['useEventListener']
  const useEventTarget: typeof import('ahooks')['useEventTarget']
  const useExternal: typeof import('ahooks')['useExternal']
  const useFavicon: typeof import('ahooks')['useFavicon']
  const useFocusWithin: typeof import('ahooks')['useFocusWithin']
  const useFullscreen: typeof import('ahooks')['useFullscreen']
  const useFusionTable: typeof import('ahooks')['useFusionTable']
  const useGetState: typeof import('ahooks')['useGetState']
  const useHistoryTravel: typeof import('ahooks')['useHistoryTravel']
  const useHover: typeof import('ahooks')['useHover']
  const useHref: typeof import('react-router-dom')['useHref']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInRouterContext: typeof import('react-router-dom')['useInRouterContext']
  const useInViewport: typeof import('ahooks')['useInViewport']
  const useInfiniteScroll: typeof import('ahooks')['useInfiniteScroll']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useInterval: typeof import('ahooks')['useInterval']
  const useIsomorphicLayoutEffect: typeof import('ahooks')['useIsomorphicLayoutEffect']
  const useKeyPress: typeof import('ahooks')['useKeyPress']
  const useLatest: typeof import('ahooks')['useLatest']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useLinkClickHandler: typeof import('react-router-dom')['useLinkClickHandler']
  const useLocalStorageState: typeof import('ahooks')['useLocalStorageState']
  const useLocation: typeof import('react-router-dom')['useLocation']
  const useLockFn: typeof import('ahooks')['useLockFn']
  const useLongPress: typeof import('ahooks')['useLongPress']
  const useMap: typeof import('ahooks')['useMap']
  const useMemo: typeof import('react')['useMemo']
  const useMemoizedFn: typeof import('ahooks')['useMemoizedFn']
  const useModal: typeof import('../hooks/use-modal')['useModal']
  const useMount: typeof import('ahooks')['useMount']
  const useMouse: typeof import('ahooks')['useMouse']
  const useMsg: typeof import('../hooks/use-msg')['useMsg']
  const useMutationObserver: typeof import('ahooks')['useMutationObserver']
  const useNavigate: typeof import('react-router-dom')['useNavigate']
  const useNavigationType: typeof import('react-router-dom')['useNavigationType']
  const useNetwork: typeof import('ahooks')['useNetwork']
  const useOutlet: typeof import('react-router-dom')['useOutlet']
  const useOutletContext: typeof import('react-router-dom')['useOutletContext']
  const usePagination: typeof import('ahooks')['usePagination']
  const useParams: typeof import('react-router-dom')['useParams']
  const usePrevious: typeof import('ahooks')['usePrevious']
  const useQueryState: typeof import('../hooks/use-query-state')['default']
  const useRafInterval: typeof import('ahooks')['useRafInterval']
  const useRafState: typeof import('ahooks')['useRafState']
  const useRafTimeout: typeof import('ahooks')['useRafTimeout']
  const useReactive: typeof import('ahooks')['useReactive']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useRequest: typeof import('ahooks')['useRequest']
  const useResetState: typeof import('ahooks')['useResetState']
  const useResolvedPath: typeof import('react-router-dom')['useResolvedPath']
  const useResponsive: typeof import('ahooks')['useResponsive']
  const useRoutes: typeof import('react-router-dom')['useRoutes']
  const useSafeState: typeof import('ahooks')['useSafeState']
  const useScroll: typeof import('ahooks')['useScroll']
  const useSearchParams: typeof import('react-router-dom')['useSearchParams']
  const useSelections: typeof import('ahooks')['useSelections']
  const useSessionStorageState: typeof import('ahooks')['useSessionStorageState']
  const useSet: typeof import('ahooks')['useSet']
  const useSetState: typeof import('../hooks/use-set-state')['default']
  const useSize: typeof import('ahooks')['useSize']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTextSelection: typeof import('ahooks')['useTextSelection']
  const useTheme: typeof import('ahooks')['useTheme']
  const useThrottle: typeof import('ahooks')['useThrottle']
  const useThrottleEffect: typeof import('ahooks')['useThrottleEffect']
  const useThrottleFn: typeof import('ahooks')['useThrottleFn']
  const useTimeout: typeof import('ahooks')['useTimeout']
  const useTitle: typeof import('../hooks/use-title')['useTitle']
  const useToggle: typeof import('ahooks')['useToggle']
  const useTrackedEffect: typeof import('ahooks')['useTrackedEffect']
  const useTransition: typeof import('react')['useTransition']
  const useUnmount: typeof import('ahooks')['useUnmount']
  const useUnmountedRef: typeof import('ahooks')['useUnmountedRef']
  const useUpdate: typeof import('ahooks')['useUpdate']
  const useUpdateEffect: typeof import('ahooks')['useUpdateEffect']
  const useUpdateLayoutEffect: typeof import('ahooks')['useUpdateLayoutEffect']
  const useVirtualList: typeof import('ahooks')['useVirtualList']
  const useWebSocket: typeof import('ahooks')['useWebSocket']
  const useWhyDidYouUpdate: typeof import('ahooks')['useWhyDidYouUpdate']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { FC } from 'react'
  import('react')
  // @ts-ignore
  export type { SetState } from '../hooks/use-set-state'
  import('../hooks/use-set-state')
  // @ts-ignore
  export type { IAModel } from '../components/ant-comm-cpns/a-modal/type'
  import('../components/ant-comm-cpns/a-modal/type')
  // @ts-ignore
  export type { IAButton } from '../components/ant-comm-cpns/index'
  import('../components/ant-comm-cpns/index')
  // @ts-ignore
  export type { IAEmpty } from '../components/ant-data-show-cpns/a-empty/type'
  import('../components/ant-data-show-cpns/a-empty/type')
  // @ts-ignore
  export type { IATabs, TabItemType } from '../components/ant-data-show-cpns/a-tabs/type'
  import('../components/ant-data-show-cpns/a-tabs/type')
  // @ts-ignore
  export type { IATimeLine, ITimeLineItem } from '../components/ant-data-show-cpns/a-time-line/type'
  import('../components/ant-data-show-cpns/a-time-line/type')
  // @ts-ignore
  export type { IATree, IATreeRef } from '../components/ant-data-show-cpns/a-tree/type'
  import('../components/ant-data-show-cpns/a-tree/type')
  // @ts-ignore
  export type { IACascader } from '../components/ant-form-cpns/a-cascader/type'
  import('../components/ant-form-cpns/a-cascader/type')
  // @ts-ignore
  export type { IACheckbox } from '../components/ant-form-cpns/a-checkbox/type'
  import('../components/ant-form-cpns/a-checkbox/type')
  // @ts-ignore
  export type { FormatType, IADateRange } from '../components/ant-form-cpns/a-date-range/type'
  import('../components/ant-form-cpns/a-date-range/type')
  // @ts-ignore
  export type { IADate } from '../components/ant-form-cpns/a-date/type'
  import('../components/ant-form-cpns/a-date/type')
  // @ts-ignore
  export type { IAInputNumber } from '../components/ant-form-cpns/a-input-number/type'
  import('../components/ant-form-cpns/a-input-number/type')
  // @ts-ignore
  export type { IAInput } from '../components/ant-form-cpns/a-input/type'
  import('../components/ant-form-cpns/a-input/type')
  // @ts-ignore
  export type { IARadio } from '../components/ant-form-cpns/a-radio/type'
  import('../components/ant-form-cpns/a-radio/type')
  // @ts-ignore
  export type { IARate } from '../components/ant-form-cpns/a-rate/type'
  import('../components/ant-form-cpns/a-rate/type')
  // @ts-ignore
  export type { IASelect } from '../components/ant-form-cpns/a-select/type'
  import('../components/ant-form-cpns/a-select/type')
  // @ts-ignore
  export type { IASlider } from '../components/ant-form-cpns/a-slider/type'
  import('../components/ant-form-cpns/a-slider/type')
  // @ts-ignore
  export type { IATextarea } from '../components/ant-form-cpns/a-textarea/type'
  import('../components/ant-form-cpns/a-textarea/type')
  // @ts-ignore
  export type { IATimeRange } from '../components/ant-form-cpns/a-time-range/type'
  import('../components/ant-form-cpns/a-time-range/type')
  // @ts-ignore
  export type { IATime } from '../components/ant-form-cpns/a-time/type'
  import('../components/ant-form-cpns/a-time/type')
  // @ts-ignore
  export type { IATreeSelect } from '../components/ant-form-cpns/a-tree-select/type'
  import('../components/ant-form-cpns/a-tree-select/type')
  // @ts-ignore
  export type { IBs } from '../components/b-scroll/type'
  import('../components/b-scroll/type')
  // @ts-ignore
  export type { IStyledCommSwiper } from '../components/comm-swiper/style'
  import('../components/comm-swiper/style')
  // @ts-ignore
  export type { ICommSwiper } from '../components/comm-swiper/type'
  import('../components/comm-swiper/type')
  // @ts-ignore
  export type { ICommTitle } from '../components/comm-title/type'
  import('../components/comm-title/type')
  // @ts-ignore
  export type { IDetailItem, IFormItem, ITableItem } from '../components/page-cpns/generate-item/index'
  import('../components/page-cpns/generate-item/index')
  // @ts-ignore
  export type { IPageButton, TBtnParams } from '../components/page-cpns/page-button/type'
  import('../components/page-cpns/page-button/type')
  // @ts-ignore
  export type { IPageSearch } from '../components/page-cpns/page-search/type'
  import('../components/page-cpns/page-search/type')
  // @ts-ignore
  export type { IPageHandle } from '../components/page-cpns/page-handle/type'
  import('../components/page-cpns/page-handle/type')
  // @ts-ignore
  export type { IPageTableConfig, IPageTable } from '../components/page-cpns/page-table/type'
  import('../components/page-cpns/page-table/type')
  // @ts-ignore
  export type { IPagePagination } from '../components/page-cpns/page-pagination/type'
  import('../components/page-cpns/page-pagination/type')
  // @ts-ignore
  export type { IPageFrom } from '../components/page-cpns/page-form/type'
  import('../components/page-cpns/page-form/type')
  // @ts-ignore
  export type { IPageDetail, IModuleItem, IDescriptionItem } from '../components/page-cpns/page-detail/type'
  import('../components/page-cpns/page-detail/type')
  // @ts-ignore
  export type { IModalForm } from '../components/page-cpns/modal-form/type'
  import('../components/page-cpns/modal-form/type')
  // @ts-ignore
  export type { ISuperPage } from '../components/page-cpns/super-page/type'
  import('../components/page-cpns/super-page/type')
  // @ts-ignore
  export type { IStyledPageHandle } from '../components/page-cpns/page-handle/style'
  import('../components/page-cpns/page-handle/style')
  // @ts-ignore
  export type { IAllFileList } from '../components/preview-files/all-file-list/type'
  import('../components/preview-files/all-file-list/type')
  // @ts-ignore
  export type { ILoadImage } from '../components/preview-files/load-image/type'
  import('../components/preview-files/load-image/type')
  // @ts-ignore
  export type { ILoadVideo } from '../components/preview-files/load-video/type'
  import('../components/preview-files/load-video/type')
  // @ts-ignore
  export type { ILoadPDF } from '../components/preview-files/load-pdf/type'
  import('../components/preview-files/load-pdf/type')
  // @ts-ignore
  export type { IPreviewFileModal, TFileList } from '../components/preview-files/preview-file-modal/type'
  import('../components/preview-files/preview-file-modal/type')
  // @ts-ignore
  export type { ISvg } from '../components/svg/type'
  import('../components/svg/type')
}
